npm must be installed before running
This rule was missing a dependency, potentially resulting in an error
like:

Error: /Stage[main]/Auvsi_suas::Server_install/Exec[npm install karma
and jasmine]/returns: change from notrun to 0 failed: Could not find
command 'npm'